#!/usr/bin/env bash

network_add_ip_alias ()
{
    if [[ -z $1 ]]; then ddt_app_error "Must pass the alias ip address as the first parameter"; fi

    text "${yel}Adding Loopback Alias IP Address:${end} '$1'"
    sudo ifconfig lo0 alias $1
}

network_remove_ip_alias ()
{
    if [[ -z $1 ]]; then ddt_app_error "Must pass the alias ip address as the first parameter"; fi

    text "${yel}Removing Loopback Alias IP Address:${end} '$1'"
    sudo ifconfig lo0 $1 delete
}

network_setup_dns ()
{
    if [[ -z $1 ]]; then ddt_app_error "Must pass the dns ip address as the first parameter"; fi

    text "DNS Servers: ${yel}'$1'${end}"
    sudo networksetup -setdnsservers 'Wi-Fi' $1

    if [ ! -z $(command -v dscacheutil) ]; then
        sudo dscacheutil -flushcache;
    fi
    sudo killall -HUP mDNSResponder
}

network_remove_dns ()
{
    dns_ip_address="1.1.1.1 1.0.0.1"
    text "DNS Servers: ${yel}'${dns_ip_address}'${end}"
    sudo networksetup -setdnsservers 'Wi-Fi' ${dns_ip_address}

    if [ ! -z $(command -v dscacheutil) ]; then
        sudo dscacheutil -flushcache;
    fi
    sudo killall -HUP mDNSResponder
}

# Function exports and parameters
export -f network_add_ip_alias
export -f network_remove_ip_alias
export -f network_setup_dns
export -f network_remove_dns
