#!/usr/bin/env bash

distro=$(lsb_release -d)

if [ -z "$(echo "${distro}" | grep "Ubuntu")" ]; then
    tool_fatal_error "Unfortunately only Ubuntu is supported, I am sure this makes you really sad :("
fi

function network_add_ip_alias ()
{
    if [[ -z $1 ]]; then tool_fatal_error "Must pass the alias ip address as the first parameter"; fi

    text "${yel}Adding Loopback Alias IP Address:${end} '$1'"
    sudo ip addr add $1/24 dev lo label lo:40
}

function network_remove_ip_alias ()
{
    if [[ -z $1 ]]; then tool_fatal_error "Must pass the alias ip address as the first parameter"; fi

    text "${yel}Removing Loopback Alias IP Address:${end} '$1'"
    sudo ip addr del $1/24 dev lo
}

function network_setup_dns_16_04 ()
{
    if [[ -z "$1" ]]; then tool_fatal_error "Must pass the dns ip address as the first parameter"; fi

    text "Updating DNS Resolver to use nameserver with ip address ${yel}'$1'${end}"
    text "${blu}Note: If you are asked for your password, it means your sudo password${end}"

    # Add the nameserver to the '/etc/resolvconf/resolv.conf.d/head' file if it does not exist, then call resolvconf to update everything
    file=/etc/resolvconf/resolv.conf.d/head
    exists=$(cat ${file} | grep "nameserver $1")
    if [ -z "${exists}" ]; then echo "nameserver $1" | sudo tee -a ${file}; fi
    sudo resolvconf -u

    text "Restarting system services after reconfiguration"
    
    file=/etc/NetworkManager/NetworkManager.conf
    if [ -f "${file}" ]; then
        sudo sed -i 's/^dns=dnsmasq/#dns=dnsmasq/i' ${file}
    fi
    
    if [ ! -z "$(sudo service --status-all | grep network-manager)" ]; then
        sudo service network-manager restart
    fi 

    sudo kill -9 $(ps aux | grep [N]etworkManager/dnsmasq | awk '{ print $2 }')
    sudo kill -9 $(ps aux | grep [d]nsmasq | awk '{ print $2 }')
}

function network_remove_dns_16_04 ()
{
    sudo sed -i 's/^#dns=dnsmasq/dns=dnsmasq/i' /etc/NetworkManager/NetworkManager.conf

    # Remove the nameserver from the resolv.conf
    sudo sed -i "/^nameserver $1/d" /etc/resolvconf/resolv.conf.d/head

    sudo resolvconf -u

    sudo service network-manager restart
}

function network_setup_dns_18_04 ()
{
    if [[ -z $1 ]]; then tool_fatal_error "Must pass the dns ip address as the first parameter"; fi

    text "${blu}DNS:${end} Writing new DNS Configuration"
    sudo sed -i "s/^[#]\?DNS=.*\?/DNS=$1/i" /etc/systemd/resolved.conf
    sudo sed -i "s/^[#]\?DNSStubListener=.*\?/DNSStubListener=no/i" /etc/systemd/resolved.conf

    sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf

    text "${blu}DNS:${end} Restarting 'systemd-resolved' to set DNS to use local DNS server"
    sudo systemctl restart systemd-resolved
}

function network_remove_dns_18_04 ()
{
    if [[ -z $1 ]]; then tool_fatal_error "Must pass the dns ip address as the first parameter"; fi

    text "${blu}DNS:${end} Resetting DNS Configuration back to sensible defaults"
    sudo sed -i "s/^DNS=$1/#DNS=/i" /etc/systemd/resolved.conf
    sudo sed -i "s/^DNSStubListener=.*\?/#DNSStubListener=yes/i" /etc/systemd/resolved.conf

    text "${blu}DNS:${end} Restarting 'systemd-resolved' to set DNS to use default resolver"
    sudo systemctl restart systemd-resolved
}

if [ ! -z "$(echo "${distro}" | grep "16.04")" ]; then
    tool_clone_function network_setup_dns_16_04 network_setup_dns
    tool_clone_function network_remove_dns_16_04 network_remove_dns
elif [ ! -z "$(echo "${distro}" | grep "18.04")" ]; then
    tool_clone_function network_setup_dns_18_04 network_setup_dns
    tool_clone_function network_remove_dns_18_04 network_remove_dns
elif [ ! -z "$(echo "${distro}" | grep "18.10")" ]; then
    tool_clone_function network_setup_dns_18_04 network_setup_dns
    tool_clone_function network_remove_dns_18_04 network_remove_dns
else
    tool_fatal_error "An unsupported version of Ubuntu was detected, given '${distro}'"
fi

# Function exports and parameters
export -f network_add_ip_alias
export -f network_remove_ip_alias
export -f network_setup_dns
export -f network_remove_dns
