#!/usr/bin/env bash

image=awscli:ddt
search=$(docker images ${image} | awk '{if(NR>1)print}')
if [ -z "${search}" ]; then
    echo -e "FROM alpine\nRUN apk add --no-cache py-pip && pip install awscli awscli-local" | docker build -t ${image} - &>/dev/null
fi

if [ -d "$HOME/.aws" ]; then
    volume="$HOME/.aws:/root/.aws"
fi

params=$@
[ "$1" == "--awslocal" ] && aws=awslocal && params=$(echo ${params} | sed "s/--awslocal//") || aws=aws

result=$(docker run -it --rm -v ${volume} ${image} ${aws} ${params})
code=$?

[ ${code} == 0 ] && echo ${result} || echo ${result} >&2
exit ${code}
